from datetime import datetime
from service.template_queries import SQL_TEMPLATES
from langchain_core.messages import HumanMessage


class PromptManager:
    def __init__(self):
        self.system_message = """
        You are a Business Consultant for an SME owner. Your mission is to:
        - Synthesize and analyze monthly sales, market, and product performance data. Each insight must be concise and direct, maintaining a formal tone without unnecessary introductions like "based on the data" or "below are." Every point should be followed by a short sentence explaining its impact on the distributor's business operations. Use clear language and avoid overly technical terms.
        - Please keep the writing brief and concise. Use positive language while still covering all trends, including increases and decreases. 
        - Focus on the current month's figures, then 
        - For datasets covering more than one month, include one additional insight of one to two sentences regarding the general trend during that period. 
        - Do not simply list the data points; instead, write a coherent narrative of the events. 
        - Avoid technical terms and prioritize clarity, focusing on the most critical areas for the distributor. 
        - The writing must be fluid and well-connected using linking words. For instance, instead of "32 products in May 2024," write "32 products showed growth in May 2024" or "32 products achieved the highest revenue in May 2024." 
        - Explain why each insight matters to help the distributor apply it in practice. 
        - Only rely on the information of the database to make your answer more reliable and credible: 
            
            1. TABLE: customers
           - Meaning: Stores client demographic data.
           - Columns:
             - Customer_Name: Full name of the client.
             - Segment: Business segment (e.g., Consumer, Corporate, Home Office).
        
        2. TABLE: locations
           - Meaning: Stores geographic data to avoid redundancy.
           - Columns:
             - Postal_Code
             - Country
             - City
             - State
             - Region
        
        3. TABLE: products
           - Meaning: Stores inventory catalog details.
           - Columns:
             - Category: High-level grouping (e.g., Furniture, Technology).
             - Sub_Category: Detailed grouping (e.g., Chairs, Phones).
             - Product_Name: Exact name of the item.
        
        4. TABLE: orders
           - Meaning: The main header for sales transactions.
           - Columns:
             - Order_Date: When the purchase occurred (Format: YYYY-MM-DD).
             - Ship_Date: When the item was dispatched.
             - Ship_Mode: Shipping method (e.g., Standard Class).
        
        5. TABLE: order_details
           - Meaning: The line items for each order containing all financial metrics.
           - Columns:
             - Sales: Total revenue generated by this line item.
             - Quantity: Number of units sold.
             - Discount: Discount applied (e.g., 0.20 means 20%).
             - Profit: Net profit after costs.
        """

        self.schema_context = """
        You are an expert MySQL Database Architect for a New Zealand SME. Your task is to translate the business owner's natural language questions into valid, optimized, and strictly READ-ONLY MySQL queries.

        ### DATABASE SCHEMA & RELATIONSHIPS
        
        1. TABLE: customers
           - Meaning: Stores client demographic data.
           - Columns:
             - Customer_ID (VARCHAR, Primary Key): Unique identifier for the client.
             - Customer_Name (VARCHAR): Full name of the client.
             - Segment (VARCHAR): Business segment (e.g., Consumer, Corporate, Home Office).
        
        2. TABLE: locations
           - Meaning: Stores geographic data to avoid redundancy.
           - Columns:
             - Postal_Code (VARCHAR, Primary Key): Unique zip code.
             - Country (VARCHAR): Country name.
             - City (VARCHAR): City name.
             - State (VARCHAR): State or district.
             - Region (VARCHAR): Broad geographic region (e.g., South, West).
        
        3. TABLE: products
           - Meaning: Stores inventory catalog details.
           - Columns:
             - Product_ID (VARCHAR, Primary Key): Unique item code.
             - Category (VARCHAR): High-level grouping (e.g., Furniture, Technology).
             - Sub_Category (VARCHAR): Detailed grouping (e.g., Chairs, Phones).
             - Product_Name (VARCHAR): Exact name of the item.
        
        4. TABLE: orders
           - Meaning: The main header for sales transactions.
           - Columns:
             - Order_ID (VARCHAR, Primary Key): Unique invoice number.
             - Order_Date (DATE): When the purchase occurred (Format: YYYY-MM-DD).
             - Ship_Date (DATE): When the item was dispatched.
             - Ship_Mode (VARCHAR): Shipping method (e.g., Standard Class).
             - Customer_ID (VARCHAR, Foreign Key): Links to customers.Customer_ID.
             - Postal_Code (VARCHAR, Foreign Key): Links to locations.Postal_Code.
        
        5. TABLE: order_details
           - Meaning: The line items for each order containing all financial metrics.
           - Columns:
             - Row_ID (INT, Primary Key): Unique row identifier.
             - Order_ID (VARCHAR, Foreign Key): Links to orders.Order_ID.
             - Product_ID (VARCHAR, Foreign Key): Links to products.Product_ID.
             - Sales (DECIMAL): Total revenue generated by this line item.
             - Quantity (INT): Number of units sold.
             - Discount (DECIMAL): Discount applied (e.g., 0.20 means 20%).
             - Profit (DECIMAL): Net profit after costs.
        
        ### STRICT RULES & CONSTRAINTS
        
        1. PRIVACY FIRST: Never SELECT `Customer_Name` unless the user explicitly asks for a specific client. Default to aggregating data (SUM, AVG, COUNT) by Segment, Region, or Category.
        2. READ-ONLY: You must NEVER generate INSERT, UPDATE, DELETE, DROP, or ALTER statements.
        3. JOIN LOGIC: If a question involves Revenue (Sales) and a Geographic Region, you MUST join `order_details` -> `orders` -> `locations`.
        4. OUTPUT FORMAT: Return ONLY the raw MySQL code. Do not include markdown formatting like ```sql or any explanatory text.

        """

    def get_date_extraction_prompt(self, user_query):
        # Dynamically grab the server's current date (e.g., "2026-05-14")
        current_date = datetime.now().strftime("%Y-%m-%d")

        return f"""
        Analyze this user query: "{user_query}"

        Today's date is: {current_date}. Use this to mathematically calculate relative terms like "today", "yesterday", or "this month".

        TASK:
        Extract the timeframe requested by the user.

        CRITICAL RULES:
        1. Always format dates strictly as "YYYY-MM-DD".
        2. If the user asks for a single specific month (e.g., "this month"), return the first day and the last day of that month.
        3. If the user asks for a single specific day, 'start_date' and 'end_date' must be exactly the same.
        4. if the user asks for multiple months, return the first day of the earlier month and the last day of the later month.

        Respond ONLY with a JSON object format:
        {{
            "start_date": "YYYY-MM-DD",
            "end_date": "YYYY-MM-DD"
        }}
        """

    def get_routing_prompt(self, user_query):
        """Prompt for Gemini to dynamically route based on queries.py"""

        # Dynamically build a list of available templates for the AI to read
        template_descriptions = ""
        for key, value in SQL_TEMPLATES.items():
            template_descriptions += f'- "{key}": {value["description"]}\n'

        return f"""
        Analyze this user query: "{user_query}"

        Here are the available pre-defined SQL templates:
        {template_descriptions}

        Does the user query perfectly match the intent of one of these templates?
        
        SCHEMA abbreviation FOR joining:
        - From products table: 'p'
        - From locations table: 'l'
        - From customers table: 'c'
        - From orders table 'o'
        
        SCHEMA CONTEXT FOR JOINING TABLES:
        - Join "product" table: INNER JOIN products AS p ON p.Product_ID = d.Product_ID
        - Join "location" table: INNER JOIN locations AS l ON l.Postal_Code = o.Postal_Code
        - Join "customer" table: INNER JOIN customers AS c ON c.Customer_ID = o.Customer_ID
        
        TASK:
        1. Identify the template based on the general description, do not include extra filters at this stage.
        2. Extract any EXTRA filters the user requested that are NOT dates. Map them to the correct table alias based on the Schema Context (e.g., if they mention 'Furniture', map it to 'p.Category').
        3. If there are extra filters, identify which tables involve to get the extra filter, then extract the joining condition in the "SCHEMA CONTEXT FOR JOINING TABLES" (for example if they mention 'Furniture', thereby two table "product" involve, then extract the joining query: "INNER JOIN product AS p ON p.Product_ID = d.Product_ID"). However, if the extra filters come from "orders" or "order_details" table, return nothing.
        4. Identify the LIMIT in the user query. The default limit is 5. (for example, if they mention "top 5" then the limit number is 5, or "lowest 12" then the limit number is 12). However, if the user mention that they want to know the highest, or lowest without specifying the number of record, set the limit default at 5.
        5. Identify the "start_date" and "end_date" in the user query and the 5-unit time window.
        
        Based on whether the question is template or adhoc, output strictly as JSON only with following format, do not create any further information and changing into list format:
        {{
            "route": "template" | "adhoc",
            "template_name": this is the matched key in the pre-defined SQL templates, example "daily_revenue" | null,
            "start_date": "YYYY-MM-DD",
            "end_date": "YYYY-MM-DD",
            "extra_filters": {{"table.column": "condition", example "l.City": "Auckland"}},
            "extra_tables":{{"table":"joining condition", example "product":"JOIN product AS p ON p.Product_ID = d.Product_ID"}} 
            "limit": this is the number to declare in limit condition in SQL query, default to 5
        }}
        
        """

    def generate_sql_prompt(self, user_query, brief):
        """Prompt for Llama 3 with 5-Unit Time Window and Limit 10 Rules"""
        current_date = datetime.now().strftime("%Y-%m-%d")

        return f"""
        You are a strictly READ-ONLY MySQL Expert for a New Zealand SME.
        
        USER QUERY: {user_query}
        
        SCHEMA:
        {self.schema_context}
        
        Brief information. 
        {brief}

        1. The query is executed in MySQL database, which does not support:
            - "NULLS LAST" syntax
        
        2. Relying on the user query, schema to generate query in MySQL database. The brief information extracted from the user query is critical to prepare the query concisely and must be strictly followed in the SQL query, especially extra condition, extra table, and limit.

        3. VISUALIZATION LIMIT (TOP/BOTTOM 10): If the result groups data (e.g., by Product, City, or Category) and will generate more than 10 rows, you MUST limit the output to 10 rows.
           - Use `ORDER BY [Metric] DESC LIMIT 10` for positive requests (e.g., highest, best, top, most).
           - Use `ORDER BY [Metric] ASC LIMIT 10` for negative requests (e.g., lowest, worst, least).
           - If the intent is specified with number of records, set the limit based on the requirement of the user (for example, if they mention "top 5" then the limit number is 5, or "lowest 12" then the limit number is 12). Or else, set default to DESC LIMIT 10.

        4. No explanations.
        
        5. Make sure every query contains aggregation function (e.g., sum, average, mean, max, min, etc.), must have "GROUP BY" for columns not in aggregation.

        
        SQL: Return ONLY valid SQL code compatible with MySQL database system.
        """

    def get_dynamic_sql_and_chart_prompt(self, raw_data):
        """
        This prompt forces Gemini to generate a safe SQL query AND
        decide the visual structure in one single JSON response.
        """
        raw_data = raw_data[:5]

        return f"""
        You are an expert Business Data Analyst AI for a New Zealand SME.
        Your task is to translate the SME owner's natural language question into a secure, read-only MySQL query AND determine the best way to visually present the results.

        USER QUESTION:
        "{raw_data}"

        VISUALIZATION RULES:
        1. "line" chart: Best for time-series data (trends over dates, months, years).
        2. "bar" chart: Best for categorical comparisons (top products, regions, segments).
        3. "pie" chart: Best for market share or percentage breakdowns.
        4. "none": Use this if the question asks for a single metric (e.g., "What is the total revenue today?") where a chart is unnecessary.

        SECURITY RULES:
        - NEVER generate INSERT, UPDATE, DELETE, or DROP statements. Only use SELECT.

        Return ONLY a valid JSON object. Do not include markdown formatting or explanations outside the JSON.
        Format:
        {{
            "chart_type": "<line | bar | pie | scatter | hist>",
            "x_col": "<exact_column_name_for_x_axis>",
            "y_col": "<exact_column_name_for_y_axis>",
        }}
        """


    def get_insight_prompt(self, raw_data, user_query):

        insight = f"""
        {self.system_message}
        
        Data: {raw_data}
        User query: {user_query}

        Task: 
        - If the Data provided above is empty (e.g., no rows/records), you MUST return EXACTLY this message and nothing else: "No sales happens on the time that you require".
        
        - If the user query asks for an extreme value (e.g., containing words like "highest", "top", "best", "most", "lowest", "worst", "least"), you must structure your analysis if the data provided has more than one item as follows:
            1. Your very first sentence must directly state the number of winning/losing item specifies by the user and its exact numerical value.
            2. Immediately after, compare this top/bottom item with the remaining items in the data (e.g., calculate the gap between 1st and 2nd place, or compare it against the average of the rest) to provide deeper insight.
            
        - You must describe exactly all data points returned that directly align with user question, then mention the key data points, analyse the trend, difference with additional data points, key intake, etc. using the data provided.
        - Provide 2 short Actionable Business Insights, not technical insight, based on this data, suggesting SME owner what to investigate further to improve the business performance or maintain it if the performance is currently good.
        - Do not bold every word; but must bold key terms and numbers.
        - Must always have the sentence "Actionable Business Insights:" in bold before the insight part to split two part of the insight. and for each business insight must be numbered.
        
        STRICT GROUNDING RULES (ANTI-HALLUCINATION):
        1. DO NOT invent, assume, or guess facts. You only know the exact metrics provided in the 'Data' array.
        2. Do NOT mention specific products, staffing, inventory, delivery, or costs UNLESS those specific words appear in the 'Data' array.
        3. If the data only shows an aggregated total (like total sales), your advice must focus on NEXT STEPS for investigation.
        4. Mention the exact numbers ONLY ONCE in the opening sentence to sound natural, formatted as with thousand seperator, without any sign (e.g., 4,182.06).
        5. Focus only on the provided data without making assumptions about future potential or offering recommendations. Avoid using absolute language.
    

        Format: English. Do not use technical terms. Focus on what the owner should DO next to improve revenue or cut costs.
        """

        return [HumanMessage(content=insight)]